# Install Rest client extension to use this requests
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### DETECT
POST http://localhost:8000/detect
content-type: application/json

{
    "movie_id": "Movies/92363371",
    "detect_every": 50
}

### TRACK
POST http://localhost:8000/track
content-type: application/json

{
    "movie_id": "Movies/92363371",
    "detect_every": 50
}

### PREDICT
POST http://localhost:8000/predict
content-type: application/json

{
    "movie_id": "Movies/92363371",
    "local": false,
    "extra_params": {
        "action": "detect",
        "detect_every": 50
    }
}

### in docker
POST http://localhost:8010/predict
content-type: application/json

{
    "movie_id": "Movies/308719",
    "local": false,
    "scene_element": 0,
    "extra_params": {
        "action": "detect",
        "detect_every": 50,
        "mdf": 0
    }
}

### in gradient
POST https://d36e439aba54842ec94938720621aefa1.clg07azjl.paperspacegradient.com/predict
content-type: application/json

{
    "movie_id": "Movies/92363371",
    "local": false,
    "extra_params": {
        "action": "track",
        "detect_every": 50
    }
}

### PREDICT IMAGE
POST http://localhost:8010/predict/image
content-type: application/json

{
    "image_id": "2402585",
    "url": "https://cs.stanford.edu/people/rak248/VG_100K/2367862.jpg",
    "extra_params": {       
    }
}