version: "3.9"
services:
  tracker:
    image: aharonamir/nebula3_experts_tracker
    ports:
      - "48005:8000"
    environment:
      ARANGO_DB: "nebula_amir"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    runtime: nvidia
